### ISSUE TITLE
log4net:ERROR Could not create Appender [HttpAppender] of type [Log4net.HttpAppender.AsyncBatchHttpAppender, Log4net.HttpAppender].

### ISSUE THREAD

**Issue by shwetajain1022** [rynmsh/log4net.http-appender#1]
Hi 
I have added following changes to my application:
Added references : log4net and Log4Net.HttpAppender from nugget packages

App.Config
-------------------------------------------------------------------------------------
<configSections>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,Log4net" />
  </configSections>
  <log4net>
    <appender name="LogFileAppender" type="log4net.Appender.RollingFileAppender">
      <param name="File" value="C:\logs\temp.log" />
      <lockingModel type="log4net.Appender.FileAppender+MinimalLock" />
      <appendToFile value="true" />
      <rollingStyle value="Size" />
      <maxSizeRollBackups value="10" />
      <maximumFileSize value="1MB" />
      <staticLogFileName value="true" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %level %logger - %message%newline" />
      </layout>
    </appender>
    <appender name="HttpAppender" type="Log4net.HttpAppender.AsyncBatchHttpAppender, Log4net.HttpAppender">
      <threshold value="Debug" />

      
      <ServiceUrl value="https://temp" />

      
      <ProjectKey value="ConsoleApp5" />

      
      <Environment value="dev|stage|prod" />

      
      <BatchMaxSize value="20" />

      
      <BatchSleepTime value="200" />

      
      

      <layout type="log4net.Layout.PatternLayout">
        <param name="ConversionPattern" value="%date [%identity] %-5level %logger - %message%newline" />
        
      </layout>
    </appender>
    <root>
      <level value="ALL" />
      <appender-ref ref="LogFileAppender" />
      <appender-ref ref="HttpAppender" />
    </root>

Program.cs
-------------------------------------------------------------------------------------------------------------------------------
class Program
    {
        private static readonly ILog Log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        static void Main(string[] args)
        {
            log4net.Config.XmlConfigurator.Configure();
            Log.Info("Info Testing");
            Log.Error("Error Testing");
            Log.Warn("Warning Testing");
            Console.Read();
        }
    }

I am getting the following error:
log4net:ERROR Could not create Appender [HttpAppender] of type [Log4net.HttpAppender.AsyncBatchHttpAppender, Log4net.HttpAppender]. Reported error follows.
System.IO.FileLoadException: Could not load file or assembly 'log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Util.SystemInfo.GetTypeFromString(Assembly relativeAssembly, String typeName, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Util.SystemInfo.GetTypeFromString(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)

===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Shweta.Jain\source\repos\ConsoleApp5\ConsoleApp5\bin\Debug\ConsoleApp5.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821
LOG: Attempting download of new URL file:///C:/Users/Shweta.Jain/source/repos/ConsoleApp5/ConsoleApp5/bin/Debug/log4net.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

log4net:ERROR Appender named [HttpAppender] not found.
'ConsoleApp5.exe' (CLR v4.0.30319: ConsoleApp5.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[7676] ConsoleApp5.exe: Program Trace' has exited with code 0 (0x0).
The program '[7676] ConsoleApp5.exe' has exited with code 0 (0x0).

Can you please fix this issue

**Comment by mabakay** [comment]
Try use full assembly declaration

`<appender name="HttpAppender" type="Log4Net.HttpAppender, Log4Net.WebServiceAppender">`

**Comment by pdbruno** [comment]
Hello, I'm getting the same error with this configuration:
`<appender name="HttpAppender" type="Log4Net.HttpAppender.AsyncBatchHttpAppender, Log4Net.HttpAppender">` using log4net v2.0.4. Is it possible that the library was compiled for v1.2.10.0?
When I change the log4net version to v1.2.10.0, I stop getting this error and the library starts working properly.
Is there something I can do to help?

**Comment by dpjha84** [comment]
Facing exactly same issue.

**Comment by mabakay** [comment]
I don't quite understand what your problem is (I am not the author of this library, just shared some tip - for clarity).

You wrote
> When I change the log4net version to v1.2.10.0, I stop getting this error and the library starts working properly.

**So you resolved your issue or not?** Type declaration is quite a simple thing. You enter the class name and namespace where it can be found. Sometimes it's necessary to type assembly name as well. But assembly is search in specified path order (https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies, https://docs.microsoft.com/pl-pl/dotnet/core/dependency-loading/default-probing). Maybe you have several versions of this library in your packages folder? Maybe different versions are referenced across solution? Hard to say without my crystal ball.
